- flow-examples/test/flow.test.ts
- packages/oocana/src/cli.ts
- packages/oocana/src/oocana.ts
- **feat: implement oocana stop session flow**
- **chore: update types**
- **fix: remove listener will effect close event**
- **feat: add stop flow test case**
> feat: implement stop flow api

- .github/workflows/publish.yml
> chore(action): publish to npm registry as well

- packages/executor/src/executor.ts
- packages/executor/src/logger.ts
- packages/executor/src/utils.ts
- packages/oocana-sdk/src/mainframe.ts
follow https://github.com/oomol/oocana-rust/pull/27 update
> feat: use identifier instead of suffix

- flow-examples/test/flow.test.ts
- packages/oocana/src/oocana.ts
- **docs: fix help**
- **feat: add tmp root argument**
- **feat: add debug mode**
> feat: add cli argument

- packages/oocana/src/oocana.ts
- **feat: add tmpDir context api**
- **feat: pass OOCANA env**
> feat: pass OOCANA_ env

- flow-examples/flows/tmp-dir/flow.oo.yaml
- flow-examples/flows/tmp-dir/scriptlets/+javascript#1.js
- flow-examples/flows/tmp-dir/scriptlets/+javascript#2.js
- flow-examples/flows/tmp-dir/scriptlets/+javascript#4.js
- flow-examples/test/flow.test.ts
- packages/executor/src/block.ts
- packages/executor/src/context.ts
- packages/executor/src/executor.ts
- packages/executor/src/service/service.ts
- packages/oocana-sdk/src/context.ts
- packages/oocana-types/src/external/context.ts
- **feat: add tmp dir pkg api**
- **feat: pass package name to context**
- **chore: add tmp dir test case**
> feat: add tmp pkg dir

- packages/executor/src/utils.ts
fix https://github.com/oomol/oocana-node/pull/46
> refactor: improve clean log

- packages/executor/src/executor.ts
- packages/executor/src/utils.ts
- packages/executor/test/argv.test.ts
- packages/oocana-types/src/block.ts
- **feat: add debug info when in debug mode**
- **feat: pass debug message on executor ready**
- **chore: add executor argv test case**
> feat: add debug info on executor ready message

- flow-examples/flows/pkg-dir/flow.oo.yaml
- flow-examples/flows/pkg-dir/scriptlets/+javascript#1.js
- flow-examples/flows/pkg-dir/scriptlets/+javascript#2.js
- flow-examples/flows/pkg-dir/scriptlets/+javascript#4.js
- flow-examples/test/flow.test.ts
- packages/executor/src/block.ts
- packages/executor/src/context.ts
- packages/executor/src/executor.ts
- packages/executor/src/service/service.ts
- packages/oocana-sdk/src/context.ts
- **chore: add pkg dir test case**
- **feat: add pkg dir**
require https://github.com/oomol/oocana-rust/pull/50 publish.
> feat: add pkg dir

- .github/actions/ovmlayer/action.yml
- executor.sh
- flow-examples/test/flow.test.ts
- install-node.sh
- packages/oocana/src/oocana.ts
this pr is for https://github.com/oomol/oocana-rust/pull/58 test and won't pass before oocana-rust publish
> feat: use new ovmlayer api and new bind path format

- cspell.json
- packages/oocana/src/oocana.ts
- **feat: change bind path format**
- **feat: check bind path format**
- **chore: add word**
> feat: update bind paths

- flow-examples/blocks/counter/block.oo.yaml
- flow-examples/blocks/counter/src/main.ts
- flow-examples/flows/slot-inline/flow.oo.yaml
- flow-examples/flows/slot-inline/scriptlets/+javascript#1.js
- flow-examples/flows/slot-subflow/flow.oo.yaml
- flow-examples/flows/slot-subflow/scriptlets/+javascript#1.js
- flow-examples/flows/slot-task/flow.oo.yaml
- flow-examples/flows/slot-task/scriptlets/+javascript#1.js
- flow-examples/package.json
- flow-examples/subflows/basic/subflow.oo.yml
- flow-examples/subflows/slot/scriptlets/+javascript#1.js
- flow-examples/subflows/slot/subflow.oo.yml
- flow-examples/test/slot.test.ts
- flow-examples/test/subflow.test.ts
- add three kinds of slot test example
- update subflow field
- fix subflow start count
> feat(test): add slot example

- .github/workflows/layer.yml
- flow-examples/packages/sub/package.oo.yaml
- **fix: add package.oo.yaml for test**
- **feat: expand layer action file scope**
> feat: expand layer action file scope

- flow-examples/.gitignore
- flow-examples/package.json
before this pr, pnpm run flow also run subflow test case. this pull request use vitest 3's feature —— run `specify the test by filename`
> chore: improve test case

- .github/workflows/layer.yml
ovmlayer api is already contained in oocana version api
> chore: improve upload logs action

- cspell.json
- flow-examples/slotflows/basic/scriptlets/+javascript#1.js
- flow-examples/slotflows/basic/slotflow.oo.yaml
- flow-examples/test/slot.test.ts
- **feat: add slotflow example**
- **add cspell**
- **feat: test slot**
> feat: add slotflow test case

- .github/workflows/layer.yml
- flow-examples/flows/slot-slotflow/flow.oo.yaml
- flow-examples/flows/slot-slotflow/scriptlets/+javascript#1.js
- flow-examples/test/slot.test.ts
- **fix: add slot-subflow test case back**
- **chore: change layer last job name**
> chore(action): add sub slotflow test case back

- .github/actions/oocana-node/action.yml
- .github/workflows/oocana-node.yml
- **chore: remove fetch-depth**
- **chore: make token optional**
- **remove token input**
> chore(action): make token optional

- flow-examples/test/flow.test.ts
- packages/oocana-sdk/src/context.ts
- packages/oocana-sdk/src/mainframe.ts
- packages/oocana-types/src/block.ts
- packages/oocana-types/src/external/reporter.ts
- **refactor: rename api**
- **rename field**
> refactor: rename event

- flow-examples/flows/absence/flow.oo.yaml
- flow-examples/test/query.test.ts
- packages/oocana-types/src/schema.ts
- packages/oocana/src/query.ts
- **feat: add query input api**
- **test: add query input api test case**
> feat: add query input api

- packages/oocana-sdk/src/context.ts
- packages/oocana-types/src/external/context.ts
implement same feature as https://github.com/oomol/oocana-python/pull/378
> feat: save table payload to csv file for better preview

- flow-examples/flows/query-block/flow.oo.yaml
- flow-examples/flows/query-block/scriptlets/+typescript#1.ts
- flow-examples/flows/query-block/scriptlets/+typescript#2.ts
- flow-examples/test/flow.test.ts
- packages/oocana-sdk/src/context.ts
- packages/oocana-sdk/src/mainframe.ts
- packages/oocana-types/src/block.ts
- packages/oocana-types/src/external/context.ts
- **feat: add query block api**
- **test: add query block api**
> feat: query block api

- cspell.json
- flow-examples/flows/query-downstream/flow.oo.yaml
- flow-examples/flows/query-downstream/scriptlets/+typescript#1.ts
- flow-examples/flows/query-downstream/scriptlets/+typescript#2.ts
- flow-examples/flows/special-output/scriptlets/+scriptlet#2.ts
- flow-examples/package.json
- flow-examples/test/flow.test.ts
- packages/oocana-sdk/src/context.ts
- packages/oocana-sdk/src/mainframe.ts
- packages/oocana-types/src/block.ts
- packages/oocana-types/src/external/context.ts
- pnpm-lock.yaml
https://github.com/oomol/oocana-rust/pull/229 's nodejs implementation
> feat: add query downstream api

- flow-examples/flows/run-block/scriptlets/+scriptlet#1.ts
- flow-examples/flows/run-block/scriptlets/+typescript#1.ts
- flow-examples/flows/run-block/scriptlets/+typescript#2.ts
- flow-examples/flows/run-pkg-block/scriptlets/+typescript#1.ts
- flow-examples/flows/run-pkg-block/scriptlets/+typescript#2.ts
- flow-examples/flows/run-subflow/scriptlets/+typescript#1.ts
- flow-examples/flows/run-subflow/scriptlets/+typescript#2.ts
- packages/oocana-sdk/src/context.ts
- packages/oocana-types/src/external/context.ts
> refactor(sdk): update runBlock api

- packages/oocana-sdk/src/context.ts
- **chore: add client id for better distinguish**
- **refactor: remove unused import**
> refactor: some refactor improve

- flow-examples/flows/subflow-progress/flow.oo.yaml
- flow-examples/flows/subflow-progress/scriptlets/+scriptlet#1.ts
- flow-examples/subflows/progress/scriptlets/+scriptlet#1.ts
- flow-examples/subflows/progress/scriptlets/+scriptlet#2.ts
- flow-examples/subflows/progress/subflow.oo.yaml
- flow-examples/test/flow.test.ts
- packages/oocana-sdk/src/context.ts
- packages/oocana-sdk/src/mainframe.ts
- packages/oocana-types/src/block.ts
- packages/oocana-types/src/external/reporter.ts
link to https://github.com/oomol/oocana-rust/pull/260
> feat: add subflow progress event

- flow-examples/blocks/aaa/block.oo.yaml
- flow-examples/blocks/aaa/package.json
- flow-examples/blocks/aaa/src/main.ts
- flow-examples/blocks/aaa/tsconfig.json
- flow-examples/blocks/aaa/tsup.config.ts
- flow-examples/package.json
- flow-examples/packages/check/blocks/check/block.oo.yaml
- flow-examples/test/block.test.ts
- flow-examples/test/flow.test.ts
- flow-examples/test/run.ts
- packages/oocana/src/oocana.ts
> feat: add run block api

- flow-examples/test/flow.test.ts
- packages/oocana-sdk/src/context.ts
- packages/oocana-types/src/external/reporter.ts
- packages/oocana-types/src/reporter.ts
https://github.com/oomol/oocana-rust/pull/276
> refactor: rename to progress

- packages/oocana/package.json
- packages/oocana/scripts/install.js
implement #313 's feature: make oocana to `node_modules/.bin`
> feat: add oocana to bin

- packages/oocana-sdk/src/context.ts
> refactor: reduce env warning count 
